dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: bMLdVDsIwpG+0aq96JbKY+7oL5cTlFHwnqwuyZobVUBRBeqqET7mLU2IeX2frd1IHVC/I1tm+LxCVhBFCJ8Zp6KuPFQVv+6xJXsQwDSw4OU7Hpdb6R0ip36ztZhZd8xznnY82gVXgjy3pJPAijODY62Xiwt2At2swHXQEax+MlFYTZPhWdbSX6y+EE+7Qcfz0mUvmSiXlYn7ScEDZ80cmskOxK3hyrpqPEs2MNMIuAlBWEvgWRR+mHy75QFr3uSQOni8aaMF3ubPX772ZR9Xq2cGdQ92m2c/00xSvgz9Iyf3JzoIaJFrLPED4TBZbBizDpdj8BXL94y7qJar3k/LgN6SotQfJi97Izf18NFSdJDS9G8ERC6VuJ7owAmHijDgGFhfnlf10uN4lvcryt3nDvwjHdfCd5AfdMJQGuDdigBUP5A56LGtvrI/X/GkG9zGvpngnA8wwPzf/ZTz3SXN1CLlZDOPZjVC5LZxvS9dTtLioDc5O5xzS73F41lUnjJHzo6Fz6iX4bLcTRkSscX2hgOZAgs0csRFhK2qZPSRts28uuCqd8RBzUKAfkUJkgwknYOJSK0ZG6pjni8DqrUB0DZwns4Yt7OdHfO1cFUdMhobLPuY+onTstLCtUwR8NDDRE2IiNXYgbgxrLYSwquVEx/qAWf3ibBcwNl1F/MdJ7w=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_ds2413.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-ds2413 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
